### PR TITLE
feat(upgrade): Upgrade PatternFly and clean site structure

### PR DESCRIPTION
**Pull request by mindreeper2420**
Update to PatternFly 3.31.0 with SASS in Core; clean site structure of duplicates

### CODE REVIEW

**Comment by catrobson** [comment]
391 files changed... what the heck Adam!  :) Do you want a review of this in any meaningful way from Dan or someone?

**Comment by mindreeper2420** [comment]
@catrobson - the fun of changing the build structure to work with the new configuration :-) I just need someone to pull this down and run it, to make sure it works properly. The automated tests and builds passed, but another manual check never hurts.

**Comment by catrobson** [comment]
@dlabrecq Can you give this a shot when you have a moment?

**Comment by dlabrecq** [comment]
I downloaded the code and ran the site (seems ok), but not certain what I'm reviewing here? It appears that we're introducing PatternFly SASS, but I don't understand why?

**Comment by mindreeper2420** [comment]
Jekyll runs off of SASS, so I'm just converting the code that used patternfly-sass to the newest release of Core.

**Comment by dlabrecq** [comment]
Ah, yes. I recall you mentioning that now.

**Pull request merged**
