### PR TITLE
Updating with Beijing and my designs

### PR DESCRIPTION
**Pull request by catrobson**
Updating with a host of design links.  Removed Sj and Sunil's old wizard links, but left your codebase designs until the new codebase designs are final.  Should we have an archived designs section somewhere?

### CODE REVIEW

**Comment by mindreeper2420** [comment]
Either an archived section, or add it as a status callouts to sort/filter by.

**Comment by catrobson** [comment]
Can I just copy the table and put another table with the header "archived" below the top one - or would that break all the searching/sorting?

I'd like to pull them out of the main table rather than tag them so its easier to find the right link for the developers.

**Comment by mindreeper2420** [comment]
Putting another table would break most of the page, just by the way the Jekyll configurations are set (each design table reuses a single layout page).

I can create another page in the Designs dropdown that just has all of the archived designs. They'd still be sortable and filterable.

**Comment by catrobson** [comment]
that makes sense to me to have an archived designs page

**Pull request merged**
